### PR TITLE
studentbeans.com added

### PR DESCRIPTION
**Pull request by Ridafarhan99**

### CODE REVIEW

**Comment by DrKain** [comment]
Have you tested and verified this does not break any functionality in the page?

**Comment by Ridafarhan99** [comment]
No i haven't. Actually I am new in this open source galaxy I might have missed this step. Can you please elaborate how can i test & verify this before making a merge request.

**Comment by DrKain** [comment]
Any added params/rules need to be tested to ensure important functionality doesn't break as a result of this package.  
The easiest way to do this would be loading the page with and without the parameters and making a note of any changes, if there's a visual change to the website then the parameter should not be removed.  
Some websites will also re-add parameters on load, so testing is required to avoid redirect loops.
This package focuses more on non-essential parameters that are used for tracking user activity or analytics.

**Comment by DrKain** [comment]
As an extra note, this should be done with almost any added/changed rule. There's a bit of a backlog at the moment because I'm unwell and unable to test them myself, but I greatly appreciate any contributions as long as they've been tested

**Pull request closed without merging**
