### PR TITLE
added rule for amp-page at ending url

### PR DESCRIPTION
**Pull request by bilalakhter**
add rule for artnet.com amp-page at ending of url

### CODE REVIEW

**Comment by DrKain** [comment]
Have you tested this? This rule appears to be invalid and would not modify the sample URL at all

**Comment by DrKain** [comment]
This should do what you wanted: `/(.*)\/amp-page$/i` 
Replace rule not required

**Comment by bilalakhter** [comment]
testing and fixing it

**Comment by bilalakhter** [comment]
it removes amp-page now when i run test

**Comment by DrKain** [comment]
Closing this because there's too many problems with your commits

**Comment by bilalakhter** [comment]
care to expain

**Comment by DrKain** [comment]
I'm surprised you don't see the problem. Your first commit was untested, invalid and didn't work. The second commit vandalized several other rules with no explanation.

**Pull request closed without merging**
